name: getfit
description: "GetFit fitness App."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  provider: ^6.1.5
  mobile_scanner: ^6.0.0
  health: ^12.0.0
  geolocator: ^13.0.4
  http: ^1.2.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/mock/users.json
  uses-material-design: true