#!/usr/bin/env sh

#run0 pacman -S texlive-latexextra

args=(--pdf-engine=xelatex
    --from markdown+hard_line_breaks
    -V mainfont="DejaVu Serif"
    -V geometry:margin=3cm
)

cd project-description/src/
pandoc project-description.md -o out.pdf "${args[@]}"
mv out.pdf ../exports/out.pdf
cd ../../

cd use-cases/src/
pandoc use-cases.md -o out.pdf "${args[@]}"
mv out.pdf ../exports/out.pdf
cd ../../

cd robustness-diagrams/src/
pandoc robustness-diagrams.md -o out.pdf "${args[@]}"
mv out.pdf ../exports/out.pdf
cd ../../

cd sequence-diagrams/src/
pandoc sequence-diagrams.md -o out.pdf "${args[@]}"
mv out.pdf ../exports/out.pdf
cd ../../

cd domain-model/src/
pandoc domain-model.md -o out.pdf "${args[@]}"
mv out.pdf ../exports/out.pdf
cd ../../

cd class-diagram/
pandoc class-diagram.md -o out.pdf "${args[@]}"
cd ../

pdfunite \
    project-description/exports/out.pdf \
    use-cases/exports/out.pdf \
    robustness-diagrams/exports/out.pdf \
    sequence-diagrams/exports/out.pdf \
    class-diagram/out.pdf \
    domain-model/exports/out.pdf \
    project-description/src/test-cases/getfit.pdf \
    report.pdf \
